Fe 36 event form flow
akademia-envelo-3/MELO-front pull request #111
Opened 2023-02-10 10:22 UTC by dominikapap

2023-02-10 10:58 UTC, abdevworks approved these changes
Kod sprawdzony. Wygląda ok.

2023-02-10 14:17 UTC, rafalfuz commented on src/app/features/event/event-form/event-form.component.html
> +                            aria-label="Typ powatarzalności wydarzenia">
literówka wpadła "powatarzalności"

2023-02-10 14:20 UTC, rafalfuz approved these changes

2023-03-02 09:53 UTC, dominikapap commented on src/app/features/event/event-form/event-form.component.html
> +                            aria-label="Typ powatarzalności wydarzenia">
poprawione

2023-03-07 07:11 UTC, akademiaEnvelo requested changes

2023-03-07 07:11 UTC, akademiaEnvelo commented on src/app/features/event/event-form/event-form.component.ts
> +    return this.newEventForm.get('eventAdditionalInfo') as FormGroup;
czemu tutaj rzutujemy na na FormGroupe typ? Powinniśmy z referencji dostać typ bardziej szczegółowy

2023-03-07 07:59 UTC, dominikapap commented on src/app/features/event/event-form/event-form.component.ts
> +    return this.newEventForm.get('eventAdditionalInfo') as FormGroup;
poprawione

2023-03-07 08:25 UTC, akademiaEnvelo approved these changes

2023-03-07 09:02 UTC, merged