Fe 13 event details view
akademia-envelo-3/MELO-front pull request #122
Opened 2023-03-07 14:32 UTC by LukaszStaniszewski

https://fe-13-event-details-view--melo-envelo.netlify.app/events
**Aby móc podejrzeć stronę należy uruchomić:** 
db: https://github.com/LukaszStaniszewski/MeloJSONServer
Oraz przejść na /events/details/1 lub kliknięciu w pierwszą kartę.

2023-03-07 14:56 UTC, dominikapap requested changes

2023-03-07 14:56 UTC, dominikapap commented on src/app/features/event/card/card.component.html
>      </a>
czym jest spowodowana zmiana ścieżki? w początkowych ustaleniach było, że szczegóły mają być na ścieżce `events/:id`?

2023-03-07 14:56 UTC, dominikapap commented on src/app/features/event/event-details/event-details.component.html
> +                        src="{{ event.mainPhoto }}" />
Czy tutaj nie powinien być jednak binding? `[src]='event.mainPhoto'`?

2023-03-07 14:56 UTC, dominikapap commented on src/app/features/event/event-details/event-details.component.html
> +    <ng-template #spinner>...Loading</ng-template>
Mamy komponent ładowania więc chyba powinien tu być użyty zamiast tekstu, pytanie jeszcze czy w każdym komponencie dajemy osobno loader czy jednak zrobić dyrektywę na wszystkie elementu które pobierają dane.

2023-03-07 14:56 UTC, dominikapap commented on src/app/features/event/event-details/event-details.component.scss
> +      background: linear-gradient(360deg, #323232 0%, #2c2120 94.13%);
może warto dodać ten gradient do pliku z kolorami?

2023-03-07 14:56 UTC, dominikapap commented on src/app/features/event/event-details/event-details.component.scss
> +      padding: 0.4rem;
tu chyba niepotrzebna pusta linia.

2023-03-07 14:56 UTC, dominikapap commented on src/app/features/event/event-details/event-details.component.scss
> +    width: $middle-side-width;
literówka powinno być `comments`

2023-03-07 14:56 UTC, dominikapap commented on src/app/features/event/event-details/event-details.component.scss
> +    align-items: center;
chyba też zbędna pusta linia

2023-03-07 14:56 UTC, dominikapap commented on src/app/features/event/event-details/event-details.component.ts
> +  vm$ = this.eventApiService.fetchEventDetails(this.route.snapshot.params['id']);
dlaczego używana jest nazwa `vm$`? później w templatce jest i tak jako `as event`, czy może byłaby lepsza bardziej opisowa nazwa?

2023-03-08 09:43 UTC, LukaszStaniszewski commented on src/app/features/event/event-details/event-details.component.scss
> +      background: linear-gradient(360deg, #323232 0%, #2c2120 94.13%);
dodałem

2023-03-08 09:43 UTC, LukaszStaniszewski commented on src/app/features/event/event-details/event-details.component.scss
> +      padding: 0.4rem;
usunąłem

2023-03-08 09:44 UTC, LukaszStaniszewski commented on src/app/features/event/event-details/event-details.component.scss
> +    width: $middle-side-width;
poprawiłem

2023-03-08 09:44 UTC, LukaszStaniszewski commented on src/app/features/event/event-details/event-details.component.scss
> +    align-items: center;
poprawiłem

2023-03-08 09:58 UTC, LukaszStaniszewski commented on src/app/features/event/card/card.component.html
>      </a>
samo events/:id kolidowało z /events, co powodowało że po przejściu na /events wczytywała się strona z szczegółami wydarzeń, zamiast z listą kart. Szukałem jakiegoś rozwiązania żeby powiedzieć routerowi że to są oddzielne ścieżki, ale chyba nie da się.

2023-03-08 10:01 UTC, LukaszStaniszewski commented on src/app/features/event/event-details/event-details.component.html
> +    <ng-template #spinner>...Loading</ng-template>
Mamy spinnera, ale tylko do infinite scrolla, a on nie pasuje za bardzo do pokazania wczytywania całej strony, dlatego tu jest tylko tekst bo ten docelowy spinner trzeba dopiero stworzyć.

2023-03-08 11:22 UTC, LukaszStaniszewski commented on src/app/features/event/event-details/event-details.component.ts
> +  vm$ = this.eventApiService.fetchEventDetails(this.route.snapshot.params['id']);
``vm$`` to View Model, odpowiada temu co widzi użytkownik. Napisałem tak aby potem w templatce nie pisać event$ as event. Jeżeli vm Cie nie przekonuje, to mogę to zmienić.

2023-03-08 11:28 UTC, LukaszStaniszewski commented on src/app/features/event/event-details/event-details.component.html
> +                        src="{{ event.mainPhoto }}" />
Zmieniłem, dzięki za tipa 😃. Nawet nie pomyślałem żeby tego użyć.

2023-03-13 10:15 UTC, dominikapap approved these changes

2023-03-14 07:16 UTC, wojky approved these changes

2023-03-14 07:16 UTC, wojky commented on src/app/features/event/event-details/member-list/event-member-list.component.html
> +                *ngIf="member.id === organizerId" />
przeniesmy strukturalna dyrektywe na poczatek

2023-03-14 08:09 UTC, LukaszStaniszewski commented on src/app/features/event/event-details/member-list/event-member-list.component.html
> +                *ngIf="member.id === organizerId" />
poprawiłem

2023-03-14 09:22 UTC, abdevworks approved these changes
ok

2023-03-14 09:35 UTC, merged