Fe 9 spinner dots
akademia-envelo-3/MELO-front pull request #34
Opened 2023-01-12 10:54 UTC by LukaszStaniszewski

@akademia-envelo-3/melo-frontend

2023-01-12 13:23 UTC, abdevworks commented on src/app/core/theme.component.ts
> +import { SpinnerDotsComponent } from '@shared/ui/spinner-dots.component';
Dodać index.ts do shared/ui i zmienić bezpośredni import '@shared/ui/spinner-dots.component' na  '@shared/ui'

2023-01-13 08:04 UTC, akademiaEnvelo requested changes

2023-01-13 08:04 UTC, akademiaEnvelo commented on src/app/core/theme.component.ts
> +    <app-spinner-dots size="md"></app-spinner-dots>
dodajmy nazwe komponentu zanim go wyswietlimy

2023-01-13 08:04 UTC, akademiaEnvelo commented on src/app/shared/ui/spinner-dots.component.scss
> +  }
animujemy elementy za pomocą `transform: translate` a nie za pomocą zmiany `position` 

https://www.sitepoint.com/atoz-css-translate-vs-position/

2023-01-13 08:37 UTC, dominikapap approved these changes
nie mam dodatkowych uwag poza tymi które już zostały zgłoszone, dobra robota :)

2023-01-16 14:08 UTC, rafalfuz approved these changes

2023-01-19 08:50 UTC, akademiaEnvelo approved these changes

2023-01-20 09:17 UTC, merged