fix: fix display of circular buttons in theme
akademia-envelo-3/MELO-front pull request #59
Opened 2023-01-19 11:04 UTC by rafalfuz

https://st-02-fix-the-display-of-buttons-in-the-storybook--melo-envelo.netlify.app/theme

2023-01-19 15:46 UTC, akademiaEnvelo approved these changes

2023-01-20 07:55 UTC, dominikapap requested changes

2023-01-20 07:55 UTC, dominikapap commented on src/app/core/theme.component.ts
> +          <p>small close</p>
Malutka sprawa, ale jeśli wszystkie nazwy piszesz z wielkiej litery to tu można poprawić żeby było spójnie

2023-01-20 07:55 UTC, dominikapap commented on src/app/core/theme.component.ts
> +          <p>small forward</p>
Tutaj też należy poprawić `small` na `Small`

2023-01-20 07:55 UTC, dominikapap commented on src/app/core/theme.component.ts
> +          <p>small text</p>
Tutaj też wielka litera na początku.

2023-01-20 08:41 UTC, dominikapap approved these changes

2023-01-20 08:41 UTC, merged