Fe 17 unit form
akademia-envelo-3/MELO-front pull request #64
Opened 2023-01-20 10:51 UTC by dominikapap

2023-01-20 13:14 UTC, rafalfuz commented on src/app/features/unit/unit-form/unit-form.scss
> +  width: clamp(280px, 80vw, 1130px);
Clamp 😍

2023-01-20 13:20 UTC, rafalfuz commented on src/app/features/unit/unit.module.ts
> +import { NgModule } from '@angular/core';
Zamiast importować cały CommonModule mozna tylko te których akurat chcesz użyć e.g.
import { NgIf, NgClass } from '@angular/common', tylko pamiętać trzeba żeby dodać je w imports
imports: [NgClass, NgIf],

2023-01-23 09:17 UTC, dominikapap commented on src/app/features/unit/unit.module.ts
> +import { NgModule } from '@angular/core';
Poprawiłam :)

2023-01-23 10:55 UTC, akademiaEnvelo commented on README.md
> +1. Jeżeli część HTML lub SCSS mają ponad 20 linijek, tworzymy dla nich osobny plik
👌

2023-01-23 11:02 UTC, akademiaEnvelo requested changes

2023-01-23 11:02 UTC, akademiaEnvelo commented on src/app/features/unit/unit-form/unit-form.scss
> +@use './src/styles' as st;
przez to, ze importujemy te style globalne nasz komponent dostaje dodatkowe je, stad komponent przekracza domyslna wartosc 4kb, napisałem w review @abdevworks jak możemy to rozwiązać wykorzystując css variables

2023-01-23 11:02 UTC, akademiaEnvelo commented on angular.json
> +                  "maximumError": "30kb"
będzie można obejść tak jak u @abdevworks

2023-01-23 11:02 UTC, akademiaEnvelo commented on src/app/features/unit/unit-form/unit-form.component.ts
> +  private unitDescriptionCtrl = this.unitForm.controls.unitDescription;
takie działanie przenieśmy proszę do getterów

2023-01-23 11:02 UTC, akademiaEnvelo commented on src/app/features/unit/unit-form/unit-form.component.ts
> +})
dlaczego w sumie ten komponent nie jest `standalone`?

2023-01-23 11:02 UTC, akademiaEnvelo commented on src/app/features/unit/unit-form/unit-form.component.ts
> +  private storageService = inject(StorageService);
najpierw injecty, potem inne pola, zachowajmy porządek :)

2023-01-23 11:02 UTC, akademiaEnvelo commented on src/app/features/unit/unit-form/unit-form.component.ts
> +    ///todo in next task: validate if unitName exist, send form and userId to backend, navigate to confirmation page
podlinkujmy ten `next task`

2023-01-23 11:02 UTC, akademiaEnvelo commented on src/app/features/unit/unit-form/unit-form.html
> +                to 255 </mat-error
te `255` powinno pochodzić z obiektu `error`, byśmy nie musieli pamiętać każdorazowo o zmianie tego komunikatu

2023-01-23 11:02 UTC, akademiaEnvelo commented on src/app/features/unit/unit-form/unit-form.html
> +                to 4000 </mat-error
jw

2023-01-23 11:02 UTC, akademiaEnvelo commented on src/app/shared/ui/circular-button/circular-button.scss
> +@use './src/styles' as st;
nie importujmy globalnych styli do arkuszy dzieci, powyzej rozwiazanie problemu

2023-01-23 12:58 UTC, dominikapap commented on src/app/features/unit/unit-form/unit-form.component.ts
> +})
Ustaliliśmy, że standalone robimy komponenty które są używane w kilku miejscach, jeśli tylko w jednym to nie standalone.

2023-01-23 12:58 UTC, dominikapap commented on src/app/features/unit/unit-form/unit-form.component.ts
> +  private storageService = inject(StorageService);
ok

2023-01-23 13:21 UTC, dominikapap commented on src/app/features/unit/unit-form/unit-form.component.ts
> +  private unitDescriptionCtrl = this.unitForm.controls.unitDescription;
przeniesione

2023-01-23 13:22 UTC, dominikapap commented on src/app/features/unit/unit-form/unit-form.component.ts
> +    ///todo in next task: validate if unitName exist, send form and userId to backend, navigate to confirmation page
podlinkowane

2023-01-23 13:58 UTC, abdevworks commented on src/app/app.module.ts
> +                component: UnitFormComponent,
Tutaj powinien być unit.module, do którego UnitForm należy lazy loadowany, a nie komponent.

2023-01-23 13:59 UTC, abdevworks commented on src/app/app.module.ts
> +import { UnitFormComponent } from './features/unit/unit-form/unit-form.component';
Ten komponent powinien należeć do unit.module.

2023-01-23 14:01 UTC, abdevworks commented on src/app/features/unit/index.ts
> +export * from './unit.module';
unit-form również powinien tu być dodany

2023-01-24 09:23 UTC, dominikapap commented on src/app/features/unit/unit-form/unit-form.html
> +                to 255 </mat-error
poprawione

2023-01-24 09:24 UTC, dominikapap commented on angular.json
> +                  "maximumError": "30kb"
zmienione z powrotem na 4kb

2023-01-24 09:25 UTC, dominikapap commented on src/app/features/unit/unit-form/unit-form.scss
> +@use './src/styles' as st;
import zmieniony tylko na plik z kolorami i breakpointami

2023-01-24 09:25 UTC, dominikapap commented on src/app/features/unit/unit-form/unit-form.html
> +                to 4000 </mat-error
poprawione

2023-01-24 09:37 UTC, dominikapap commented on src/app/shared/ui/circular-button/circular-button.scss
> +@use './src/styles' as st;
poprawione

2023-01-24 09:53 UTC, dominikapap commented on src/app/app.module.ts
> +                component: UnitFormComponent,
poprawione

2023-01-24 09:53 UTC, dominikapap commented on src/app/features/unit/index.ts
> +export * from './unit.module';
dodane

2023-01-24 09:53 UTC, dominikapap commented on src/app/app.module.ts
> +import { UnitFormComponent } from './features/unit/unit-form/unit-form.component';
poprawione

2023-01-26 06:19 UTC, akademiaEnvelo approved these changes

2023-01-26 06:19 UTC, akademiaEnvelo commented on src/app/features/unit/unit-form/unit-form.component.ts
> +    controlName.statusChanges.subscribe(() => {
tutaj mamy subskrypcje hot, ktora tez powinna zostać wyczyszczona

2023-01-26 10:06 UTC, dominikapap commented on src/app/features/unit/unit-form/unit-form.component.ts
> +    controlName.statusChanges.subscribe(() => {
poprawione

2023-01-26 10:15 UTC, rafalfuz approved these changes
Najs

2023-01-26 10:27 UTC, merged