St 03 styles file structure
akademia-envelo-3/MELO-front pull request #68
Opened 2023-01-23 12:50 UTC by dominikapap

2023-01-23 13:18 UTC, abdevworks approved these changes
Zmiany wprowadzone zgodnie z ustaleniami.

2023-01-23 13:54 UTC, LukaszStaniszewski requested changes

2023-01-23 13:54 UTC, LukaszStaniszewski commented on src/styles/_colors.scss
> +);
Te kolory należą do ustawień Materiala. Może mogłabyś przenieś je do folderu z materialem ?

2023-01-23 14:57 UTC, akademiaEnvelo approved these changes

2023-01-24 08:12 UTC, dominikapap commented on src/styles/_colors.scss
> +);
przeniesione

2023-01-24 08:14 UTC, rafalfuz approved these changes

2023-01-24 08:16 UTC, LukaszStaniszewski reviewed
Wszystko ok!

2023-01-24 08:17 UTC, LukaszStaniszewski approved these changes

2023-01-24 08:18 UTC, merged