Fe 30 resize power con
akademia-envelo-3/MELO-front pull request #80
Opened 2023-01-26 08:31 UTC by rafalfuz

https://fe-30-resize-power-con--melo-envelo.netlify.app/theme

2023-01-26 08:42 UTC, dominikapap approved these changes

2023-01-27 11:53 UTC, LukaszStaniszewski requested changes

2023-01-27 11:53 UTC, LukaszStaniszewski commented on src/app/shared/ui/power-icon/power-icon.component.ts
>  type ThemeOptions = 'primary' | 'secondary' | 'teriarty';
Tu jest literówka powinno być **_tertiary_**, zamiast _teriarty_.

2023-01-27 13:56 UTC, rafalfuz commented on src/app/shared/ui/power-icon/power-icon.component.ts
>  type ThemeOptions = 'primary' | 'secondary' | 'teriarty';
Done

2023-01-30 10:31 UTC, akademiaEnvelo commented on src/app/shared/ui/power-icon/power-icon.component.ts
> +// import { NgIf, NgClass } from '@angular/common';
oj

2023-01-30 10:32 UTC, akademiaEnvelo approved these changes

2023-01-30 10:35 UTC, rafalfuz commented on src/app/shared/ui/power-icon/power-icon.component.ts
> +// import { NgIf, NgClass } from '@angular/common';
Done

2023-01-30 11:17 UTC, LukaszStaniszewski approved these changes

2023-01-31 12:11 UTC, fbrv01 approved these changes
OK

2023-01-31 14:11 UTC, merged