St 01 replace button
akademia-envelo-3/MELO-front pull request #81
Opened 2023-01-26 14:08 UTC by dominikapap

2023-01-27 09:03 UTC, LukaszStaniszewski requested changes

2023-01-27 09:03 UTC, LukaszStaniszewski commented on src/app/shared/page-not-found/page-not-found.component.ts
>          <p class=" pnf-container__text text-body-big">Wróć do strony głównej</p>
Może  ```<p></p>``` powinien mieć nazwę klasy rozszerzającą klasę diva w którym jest zagnieżdżony,                 np: pnf-container__redirect__text, albo odwołać się do niego za pomocą znacznika, ```pnf-container__redirect > p ```

2023-01-27 09:48 UTC, dominikapap commented on src/app/shared/page-not-found/page-not-found.component.ts
>          <p class=" pnf-container__text text-body-big">Wróć do strony głównej</p>
Zgodnie z [BEM](https://getbem.com/faq/#css-nested-elements) nie powinno się robić nestowania nazw więcej niż jeden poziom, mogę zmienić na `pnf-container__redirect > p` jeśli `pnf-container__text` jest nieczytelne.

2023-01-27 13:20 UTC, LukaszStaniszewski commented on src/app/shared/page-not-found/page-not-found.component.ts
>          <p class=" pnf-container__text text-body-big">Wróć do strony głównej</p>
poczytam o tym w ramach samodoskonalenia:), dzięki za link

2023-01-30 08:21 UTC, rafalfuz approved these changes

2023-01-30 08:30 UTC, LukaszStaniszewski approved these changes

2023-01-30 08:34 UTC, akademiaEnvelo approved these changes

2023-01-30 08:35 UTC, merged