feat: installed Ngx Cookies Package, add authentication with JWT
akademia-envelo-3/MELO-front pull request #82
Opened 2023-01-26 19:23 UTC by LukaszStaniszewski

@akademia-envelo-3/melo-frontend 
- #13

2023-01-27 08:02 UTC, dominikapap commented on src/app/shared/inject-hooks.ts
> +}
fajnie, że dodałeś plik do hooków :)

2023-01-27 08:12 UTC, dominikapap approved these changes

2023-01-27 15:00 UTC, LukaszStaniszewski commented on src/app/shared/inject-hooks.ts
> +}
dzięki

2023-01-30 14:27 UTC, akademiaEnvelo requested changes

2023-01-30 14:27 UTC, akademiaEnvelo commented on src/app/features/auth/auth/auth.component.ts
> +      this.authService.login(this.form.value as LoginCredentials);
użyjmy zamiast `value` `getRawValue()` co powinno rozwiązać problem castowania typu

2023-01-30 14:27 UTC, akademiaEnvelo commented on src/app/shared/inject-hooks.ts
> +}
proponuję trzymać hook'a na plik

2023-01-30 14:27 UTC, akademiaEnvelo commented on src/app/features/auth/auth/auth.service.ts
> +  private auth$$ = new BehaviorSubject<AuthState>({ auth: 'none', user: null });
nie trzymamy tego w ngrx?

2023-02-02 11:18 UTC, closed without merging